version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: donaton-frontend
    ports:
      - "3000:3000"
    networks:
      - donaton-net
    
    # Configuramos el Watcher nativo
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .next/

# Declaramos la red externa para que busque la que creó el backend
networks:
  donaton-net:
    external: true
    name: donaton-global-net